name: buf

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          lint: true
          format: true
          breaking: true
          breaking_against: "https://github.com/anolishq/anolis-protocol.git#branch=main"
